In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3351, 2046, 8161, 5574],
 [3351, 2046, 8161, 6347],
 [3351, 350, 8161, 5930],
 [5364, 2779, 167, 9176, 936],
 [5364, 2779, 167, 9176, 4299],
 [958, 3351, 5218, 8161, 415],
 [1637, 5327, 2840, 9176]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3351 2046 8161 5574]
 [   0    0    0    0 3351 2046 8161 6347]
 [   0    0    0    0 3351  350 8161 5930]
 [   0    0    0 5364 2779  167 9176  936]
 [   0    0    0 5364 2779  167 9176 4299]
 [   0    0    0  958 3351 5218 8161  415]
 [   0    0    0    0 1637 5327 2840 9176]]


In [10]:
## feature representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Documents\anaconda\envs\deeplearning_env\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [ 0.02813916,  0.02858159,  0.01376841,  0.00805948,
         -0.00309182, -0.01463513,  0.02234245,  0.03263353,
          0.04653214,  0.00466822],
        [ 0.02770999, -0.0117417 ,  0.00518046, -0.02069693,
          0.02463986,  0.02944168,  0.0176829 ,  0.00595867,
          0.03566451, -0.0369078 ],
        [ 0.01059585,  0.01113505, -0.01654031,  0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3351, 2046, 8161, 5574])

In [23]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [-0.03060596,  0.00988634, -0.00284202, -0.01885705,
          0.01086624,  0.03237741,  0.00809599,  0.03897447,
          0.04046244, -0.01057806],
        [ 0.02813916,  0.02858159,  0.01376841,  0.00805948,
         -0.00309182, -0.01463513,  0.02234245,  0.03263353,
          0.04653214,  0.00466822],
        [ 0.02770999, -0.0117417 ,  0.00518046, -0.02069693,
          0.02463986,  0.02944168,  0.0176829 ,  0.00595867,
          0.03566451, -0.0369078 ],
        [ 0.01059585,  0.01113505, -0.01654031,  0.0